[versions]
# Core
java = "21"

# Spring
spring-boot = "4.0.0"
spring-dependency-management = "1.1.7"

# Testing
junit = "5.10.0"

# Tools
lombok = "1.18.30"
mapstruct = "1.5.5.Final"

# Database
postgresql = "42.7.1"

[libraries]
# Testing
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }

# Lombok
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

# Spring Boot Starters
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }

# MapStruct
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }

# Database
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }

[bundles]
# Agrupaci√≥n de dependencias relacionadas
spring-web = ["spring-boot-starter-web", "spring-boot-starter-actuator"]
spring-persistence = ["spring-boot-starter-jpa", "postgresql"]
testing = ["junit-jupiter"]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
